### ISSUE TITLE
Label key comparison in duplicate measurements

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#16]
I have noticed in the duplicate measurements that the label_key selected for each baseline type may not match the label stored in self.labels for each redundant type. if this is the case, the program errors out and claims in baseline type does not exist. Instead should it search to see if one of labels in that baseline type is stored in the self.labels? this could be time consuming, but would check if the antenna interferometer object contains any baselines of that type instead of just raising and error and quitting the program.

here is an image showing that one of the baselines in the group was contained in the self.labels while the chosen 'key' was not. This resulted in an exception being raised even though that baseline type existed.

![image](https://user-images.githubusercontent.com/8646829/30878940-da512412-a2b2-11e7-93f9-b4994e2288d1.png)

**Comment by nithyanandan** [comment]
There have been many fixes along the way. Not sure if they fixed this problem.

When I tried it, I found that the group keys `self.blgroups.keys()` matches the labels in `self.labels` (see below though I have used simvis in place of self in the code snippet below).

Have you tried figuring out the group key based on the input label you are interested in? These can be obtained by using the attribute bl_reversemap as follows.

<img width="761" alt="screen shot 2017-10-27 at 3 44 24 pm" src="https://user-images.githubusercontent.com/5192621/32126529-68b585fc-bb2e-11e7-991d-ef6b78de9241.png">

Once you get the group key, you can then access all other baseline labels in that group.

Does this help?

**Comment by nithyanandan** [comment]
Another issue I notice with the above approach is when the input label tuple is reversed
`inp_label = ('7', '16')`
Then 
`blgrpkey_for_inp_label = simvis.bl_reversemap[inp_label]`
yields a KeyError even though the input label is just reversed.

**Comment by nithyanandan** [comment]
In 7411561 (branch issue-16), added functionality to find the keys of baseline groups for a list of input baselines and also the redundant baseline labels in groups in which the input baseline belongs. For example, 

```
ipdb> inp_labels = [('0','0'), ('12','2'), ('6','4'), ('-2','100')]
ipdb> blkeys, flips = simvis.getBaselineGroupKeys(inp_labels)
ipdb> blkeys
[None, ('1', '11'), ('10', '8'), None]
ipdb> flips
[None, True, False, None]
ipdb> blgrps, flips = simvis.getBaselinesInGroups(inp_labels)
ipdb> blgrps
[None, array([('1', '11'), ('2', '12'), ('3', '13'), ('8', '4'), ('9', '5'),
       ('10', '6')], 
      dtype=[('A2', 'S2'), ('A1', 'S2')]), array([('10', '8'), ('13', '11'), ('2', '0'), ('3', '1'), ('6', '4'),
       ('7', '5'), ('16', '14'), ('17', '15'), ('18', '16')], 
      dtype=[('A2', 'S2'), ('A1', 'S2')]), None]
ipdb> flips
[None, True, False, None]
ipdb>
```
`blkeys` contains the keys to groups under which each of the labels in `inp_labels` fall. 
`blgrps` is a list that shows the redundant baselines in the group under which each of the labels in `inp_labels` fall.
`flips` tell you if the baseline label ordering had to be flipped in order to find the baseline keys. `True` means they had to be flipped, `False` means they were found as is. 
`None` implies that the given input label in `inp_labels` was not found even when flipped.

This fixes the "finding the flipped baseline label" issue mentioned in the comment above. Does it address the original issue?

**Comment by mkolopanis** [comment]
so I am currently on `git describe` version:  `v1.11-334-g69517a4` and make_redundant_visibilities.py runs to completion on my simulated data file. Looks like i got 8001 unique baselines from a HERA-127 simulation. This seems to make sense, `127*126/2. = 8001.` I'm willing to say that this issue has been resolved through some of the commits leading up to this test.
